### ISSUE TITLE
search metafiles in classpath

### ISSUE THREAD

**Issue by romani** [checkstyle/metadata-gen#32]
we need to think on how to search metafiles in classpath in runtime of plugins:
 - make prefix for all metafiles like "checkstylemeta-AbbreviationNameCheck.xml"
- put all files in special folder/package "com/mycompany/checkstylemeta/"

I think special package is best option for us 
`com.puppycrawl.tools.checkstyle.meta.checks.name.AbbreviationNameCheck.xml` for standard checks
and file prefix for `checkstylemeta-AbbreviationNameCheck.xml` for thirdparties at any package they like
so plugins will load all standard Check/Filters meta by hardcoded package name (and all subpackages). 
BUT third partiy Checks (sevntu) can place them in any package and just name xml files with prefix checkstylemeta

**Comment by gaurabdg** [comment]
Lets break down the process.

Starting point - Plugin will have no clue what checks are present.
Solution:
1. use https://github.com/ronmamo/reflections to get all XML files in the classpath `com.mycompany.cs-meta`
2. checkstyle will provide a `module-list.xml` file. We will provide a function to read it and return `List<String> modulePaths` from where the plugin can call `XMLReader.read(InputStream(modulePath))` for each modulePaths.

**Comment by strkkk** [comment]
Packages for generated files can have same names as packages of checks they were generated from

**Comment by gaurabdg** [comment]
> Packages for generated files can have same names as packages of checks they were generated from

Yes, that we'll do.

@strkkk But I was thinking of supplying the function to read all xml and provide `List<ModuleDetails>` ourselves only, as all plugins will need this util(eclipse and sonar do require) Shall I proceed?

**Comment by strkkk** [comment]
`Shall I proceed?`
you mean to group them by package or what?

**Comment by gaurabdg** [comment]
> `Shall I proceed?`
> you mean to group them by package or what?

No, this
>  I was thinking of supplying the function to read all xml and provide `List<ModuleDetails>` ourselves only, as all plugins will need this util(eclipse and sonar do require)

**Comment by romani** [comment]
You can proceed, but keep in mind this library should stay in generator project or plugins, not a checkstyle. So util implementation  will be plugins, copy paste is okay.

I still need details in how search of metadata is done now, without library.

**Comment by gaurabdg** [comment]
@romani Till now I kept the library in plugin only. But since we want to support that functionality from checkstyle only, we have to keep the library in checkstyle.

**Comment by gaurabdg** [comment]
@romani Shall we close this as the feature has been merged?

**Comment by romani** [comment]
Please reference PR where it was fixed

**Comment by gaurabdg** [comment]
https://github.com/checkstyle/metadata-gen/pull/33 has the implemented function `readAllModules()`, which fixes this.

**Comment by romani** [comment]
I think special package is best option for us `com.puppycrawl.tools.checkstyle.meta.checks.name.AbbreviationNameCheck.xml` for standard checks 
and file prefix for `checkstylemeta-AbbreviationNameCheck.xml` for thirdparties
so plugins will load all standard Check/Filters meta by hardcoded package name (and all subpackages). BUT third partiy Checks (sevntu) can place them in any package and just name xml files with prefix checkstylemeta

**Comment by gaurabdg** [comment]
> I think special package is best option for us `com.puppycrawl.tools.checkstyle.meta.checks.name.AbbreviationNameCheck.xml` for standard checks
> and file prefix for `checkstylemeta-AbbreviationNameCheck.xml` for thirdparties
> so plugins will load all standard Check/Filters meta by hardcoded package name (and all subpackages). BUT third partiy Checks (sevntu) can place them in any package and just name xml files with prefix checkstylemeta

@romani Agreed, done for standard checks, will send a new PR for sevntu/third party.

**Comment by romani** [comment]
`checkstylemeta-` support is not done and probably it should be hosted in plugins.

Some fix is merged, we will see how it works in reallife

**Comment by gaurabdg** [comment]
> `checkstylemeta-` support is not done and probably it should be hosted in plugins.

Yes, I was planning to send in new PR, thinking that there would be some more changes which pop up while testing
