### ISSUE TITLE
Future Tasks Reminder of Paragraph Tag Wrapping And Example Differentiator

### ISSUE THREAD

**Issue by gaurabdg** [checkstyle/metadata-gen#34]
There are two parsing problems to solve in the future:
1. Current scraping logic only creates text from a subtree whose parent it either `<p>` or `<li>` to keep the code simple.
So, when in description there are some other HTML tags, for example `<pre>` on the "top level", that is not inside `<p>` tags, they are ignored. So, to fix this we have to ensure in javadocs, that either we wrap the whole description in one `<p>` or wrap each `<pre>` with `<p>` and each </pre>` with `</p>`

Here is the difference when wrapped with `<p>` tags, the orher HTMLtags dont get missed out:
![Screenshot_20200731_211549](https://user-images.githubusercontent.com/23253816/89052705-bb949c80-d373-11ea-86ea-8b2f64d05424.png)

2. Addition of a proper marker to differentiate the beginning of example section of the module, in absence of properties.

How the description should look like and what it is now:
![Screenshot_20200731_211603](https://user-images.githubusercontent.com/23253816/89052695-b899ac00-d373-11ea-90e1-376d26030ea0.png)

The solution is to add " * Examples: ".

**Comment by romani** [comment]
@gaurabdg , can you explain why you can not simply grab to description all the beginning till
```
 * <ul>
 * <li>
 * Property
```
?

-----

as I already mentioned, EmptyBlock description should be fixed to remove example of config and execution to "Examples" section.

**Comment by gaurabdg** [comment]
> @gaurabdg , can you explain why you can not simply grab to description all the beginning till
> 
> ```
>  * <ul>
>  * <li>
>  * Property
> ```
> 
> ?
> 
> as I already mentioned, EmptyBlock description should be fixed to remove example of config and execution to "Examples" section.

Yes, I used this logic only. But what about checks which dont have properties? For example, `UpperEllCheck`?

**Comment by romani** [comment]
https://github.com/checkstyle/checkstyle/blob/86e27543209734aba972691e018289095e5a6851/src/main/java/com/puppycrawl/tools/checkstyle/checks/UpperEllCheck.java#L38

Read up to
```
* <p>
 * To configure the check:
```
If some checks do not have such words, let's update them.

**Comment by gaurabdg** [comment]
> If some checks do not have such words, let's update them.

Yes, since it is not consistent, a marker would be needed. Why not a clear indication like ` * Examples:`?

**Comment by romani** [comment]
Ok, Please do. But do not postpone update, please send first PR today

**Comment by gaurabdg** [comment]
> Ok, Please do. But do not postpone update, please send first PR today

https://github.com/checkstyle/checkstyle/pull/8597

**Comment by romani** [comment]
fix is merged.
