### ISSUE TITLE
LineLengthCheck.fileExtensions default value

### ISSUE THREAD

**Issue by romani** [checkstyle/metadata-gen#37]
https://github.com/checkstyle/metadata-gen/pull/30/files#diff-3fac7ed9648e7d99f0d52cd7e7b57387R29

```
<property name="fileExtensions" type="java.lang.String[]" default-value="all files">
          <description><![CDATA[Specify file extensions that are accepted.]]></description>
        </property>
```

`all files` is not good default value. We need to fix javadoc. It is what we mean and how it will be interpreted, but it is not a value

**Comment by gaurabdg** [comment]
> all files is not good default value.

Please let me know what default value you want here.

**Comment by romani** [comment]
Same as in code
https://github.com/checkstyle/checkstyle/blob/05c9741bd19646ff8cd8a34d578cade337899cdb/src/main/java/com/puppycrawl/tools/checkstyle/api/AbstractFileSetCheck.java#L49

**Comment by romani** [comment]
fix is merged to checkstyle repo https://github.com/checkstyle/checkstyle/issues/8633
