### ISSUE TITLE
Name of Checks should not have "Check" suffix

### ISSUE THREAD

**Issue by romani** [checkstyle/metadata-gen#39]
from generated metadata files:
`<check name="InterfaceMemberImpliedModifierCheck" ....`

it should be `<check name="InterfaceMemberImpliedModifier"`
same as we print in HTML website - https://checkstyle.org/config_modifier.html#InterfaceMemberImpliedModifier

is used want class name he has `fully-qualified-name="com.puppycrawl.tools.checkstyle.checks.modifier.InterfaceMemberImpliedModifierCheck"`

for some historical reason it is only applicable to Checks, not a Filters. Filters should stay the same - name of class

**Comment by gaurabdg** [comment]
What do you mean by this?

> is used want class name he has `fully-qualified-name="com.puppycrawl.tools.checkstyle.checks.modifier.InterfaceMemberImpliedModifierCheck"`

Fully qualified name should stay as is right?

**Comment by romani** [comment]
Typo

>is used

If user
