### ISSUE TITLE
null default values looks like string value 'null'

### ISSUE THREAD

**Issue by romani** [checkstyle/metadata-gen#43]
I noticed in meta files `<property name="minimumMessage" type="java.lang.String" default-value="null">`

we need to think if we can make some distinction between `null` as string vs actual `null`.

is there any ides ???

**Comment by muhlba91** [comment]
also see addendum at #54

**Comment by rnveach** [comment]
I assume the XML is coming from our creation?

I see 2 options:
1)
Change type from whatever it is to something that signifies a null object. I was originally thinking of making up some fictional `null` type, but what about `java.lang.Object`. This would make more sense when `null` is specified as its value, signifying a null object.
2)
Other option is to add a new attribute like `null="true"` or `isNull="true"`.

I prefer option 1.

**Comment by muhlba91** [comment]
@rnveach @romani let's move discussion over to #54 ?

in terms of your proposal, i'd prefer option 2 as it's more explicit that it's actually null. what if you have `Integer` and when you assign `Object` to it relying on the metadata? this can cause errors relatively easy, imo.
further discussion moved to #54.

**Comment by romani** [comment]
we need to hardcode `null` in logic as special value, it is unfortunate hack as we have no time to fix it in better way. We discovered it too late.

**Comment by romani** [comment]
now it is without value, presumably :
```
src/main/resources/com/puppycrawl/tools/checkstyle/meta/checks/DescendantTokenCheck.xml
38-               <description>Control whether the number of tokens found
39- should be calculated from the sum of the individual token counts.</description>
40-            </property>
41:            <property name="minimumMessage" type="java.lang.String">
42-               <description>Define the violation message
43- when the minimum count is not reached.</description>

```
