### ISSUE TITLE
We need to prove that default configs works fine

### ISSUE THREAD

**Issue by romani** [checkstyle/metadata-gen#45]
As we detected few problems with default values during metadata generation like:
- explanation of value is used instead real value
- null values https://github.com/checkstyle/metadata-gen/issues/43
- arrays are defined as `"{}"`
- .... there ... might be something else left.

We need to review all Checks to make sure their default are correct values for setter of Classes and it is same as Check class mean by default.
User should be always to provide same default values and get the same result.

**Comment by muhlba91** [comment]
addendum in #54
