### ISSUE TITLE
CRITICAL: invalid defaults

### ISSUE THREAD

**Issue by muhlba91** [checkstyle/metadata-gen#54]
The following defaults raise exceptions when used in SQ checks. Hence, default SQ configuration does not work.

- HeaderCheck & RegexpHeaderCheck: `illegal value 'null' for property 'headerFile'`
- DescendantTokenCheck: `illegal value 'java.lang.Integer.MAX_VALUE' for property 'maximumDepth'`; `Error converting from 'String' to 'Integer' For input string: "java.lang.Integer.MAX_VALUE"`
- ImportControlCheck: `illegal value 'null' for property 'file'`
- SuppressWarningsHolderCheck: `Unable to instantiate 'SuppressWarningsHolderCheck' class, it is also not possible to instantiate it as .SuppressWarningsHolderCheck, SuppressWarningsHolderCheckCheck, .SuppressWarningsHolderCheckCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.`

**Comment by muhlba91** [comment]
this prevents release of https://github.com/checkstyle/sonar-checkstyle/issues/302

**Comment by gaurabdg** [comment]
@muhlba91 
> * SuppressWarningsHolderCheck: `Unable to instantiate 'SuppressWarningsHolderCheck' class, it is also not possible to instantiate it as .SuppressWarningsHolderCheck, SuppressWarningsHolderCheckCheck, .SuppressWarningsHolderCheckCheck. Please recheck that class name is specified as canonical name or read how to configure short name usage https://checkstyle.org/config.html#Packages. Please also recheck that provided ClassLoader to Checker is configured correctly.`
This is resolved in https://github.com/checkstyle/sonar-checkstyle/pull/312, as I have removed the `Check` suffix

**Comment by gaurabdg** [comment]
@muhlba91 It seems sonar dont have any default values in their `rules.xml` file. So I'll update the code to not set default values in sonar metadata.

**Comment by muhlba91** [comment]
@gaurabdg yes, those are coming from checkstyle with the checkstyle config generated by sonar.
you can reproduce them this way:
- setup sonar correctly and install the master branch's jar file of the plugin
- in quality profiles, either create a new (default) one or modify the current default profile to:
  - click activate more rules
  - filter by Reporitory -> Checkstyle
  - click Bulk Apply -> Activate in ...
- execute analysis
(alternatively, instead of applying all checks, you can explicitly filter for them and activate those with default values.)
n.b.: i had a clean installation of SQ 7.9-community running.

@romani @gaurabdg i agree, either the javadoc reflects a working default value or we do some sanity checks around them. e.e.g if it's null, we do not return `"null"` but `null` (OK, i mean the null value instead of a string :D).
this should solve 3 out of the 5 errors already.
if removing the `Check` suffix solved the other one, we are then only left with the MAX_VALUE one.
i am not sure if we can set this one in the javadoc to the actual value and not the reference as the whole point of MAX_VALUE is to be value agnostic. maybe it would make more sense to include a list of those "special values" to be resolved when reading the javadoc?

**Comment by romani** [comment]
>DescendantTokenCheck: illegal value 'java.lang.Integer.MAX_VALUE' for property 'maximumDepth'; Error converting from 'String' to 'Integer' For input string: "java.lang.Integer.MAX_VALUE"

We need to use exact value of this constant.
@gaurabdg , please update javadoc in checkstyle.
User should be able to copy default value, pase it to Check and should work the same as not defining property at all.

>illegal value 'null' for property

This is bad design of Checks, unfortunately plugins need to support it for now. If user write no value ( empty string) plugin need to interpret it as `null` java value.
Please open issues on Checks to change behavior to be able to set default value, separate issue in each Checks.

**Comment by gaurabdg** [comment]
@muhlba91 @romani On some digging I found out that default values which cant be put directly into the checkstyle module instantiation for ex:
Properties of `HeaderCheck`
`null`: https://github.com/checkstyle/checkstyle/blob/6f58247b85ff4d74eb22dbd8c51d72b69fe51839/src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java#L72
`charset of parent module`: https://github.com/checkstyle/checkstyle/blob/6f58247b85ff4d74eb22dbd8c51d72b69fe51839/src/main/java/com/puppycrawl/tools/checkstyle/checks/header/HeaderCheck.java#L64

Metadatafiles of both
sonar: https://github.com/checkstyle/sonar-checkstyle/blob/b1bbe372cf90668c13ea1b74cae9f0d1d693991f/src/main/resources/org/sonar/plugins/checkstyle/rules.xml#L3
eclipse-cs: https://github.com/checkstyle/eclipse-cs/blob/23b9fd3fc4d1913b2a874b5b648b4a022643eeae/net.sf.eclipsecs.checkstyle/metadata/com/puppycrawl/tools/checkstyle/checks/header/checkstyle-metadata.xml#L8
dont have the default values noted down.
So I think we should also not update for cases like this.

**Comment by muhlba91** [comment]
if we don't integrate those cases in metadata i see those use cases now:
1) plugins not using metadata will work without problems. they do not specify a default value and CS initiates them properly - remember, before integrating metadata in e.g. sonar we didn't have this problem
2) plugins relying on only metadata will have problems as they need to somehow keep a list of checks and appropriate parameters they need to overwrite and set better default values.
3) a mix between both, like in sonar now. we apply 1) where possible as those are old checks and 2) for new checks or when old checks get moved to metadata only.

to me, 2) (and, therefore, 3) ) is not convenient and, @romani please correct me, is not the purpose of creating metadata if plugins/extensions have to take care of each check again and maybe overwrite information metadata in the main CS project provides.

hence, plugins needs to rely on the metadata provided. if metadata returns the null String the plugin assumes this is correct. if it's actually the null value, the metadata (at least library calls) have to take care of this and return the correct value.

as with #56 the solution can and probably will be hybrid too. one example with `charset of parent module` might need to get fixed in the javadoc - we cannot process it other than saying, yup. this is just the value now. "bad luck".
but in case if `"null"` i believe we should mitigate it in metadata, and maybe also update the javadoc if one sees fit/need for it.

@romani please comment as well to have a joint decision on how to proceed further.
i believe we should at least add the null cvalue check into the metadata library plugins call/execute and, if (timewise) possible, probably also into the generated xml as `isNull="true|false"`.
the other error @gaurabdg mentioned with the charset should probably be fixed in the javadoc somehow, i believe.

**Comment by gaurabdg** [comment]
We can do one thing, in javadocs we can introduce a property something like `safeToUse` which will let plugins know whether they can be used to instantiate or not. 
Till now sonar/eclipse didnt use to store such default values(null/charset of parent) in their metadata, so we can skip now also. Anyways checkstyle modules will get instantiated with default values, irrespective of they are present in the metadata.

Those values should be only for users to view, not actually be used in module instantiation

**Comment by gaurabdg** [comment]
Only null is problematic I guess

**Comment by muhlba91** [comment]
yes, i  believe we agree on the `null` issue and we should definitely fix that one.

commenting @romani from before:
`User should be able to copy default value, pase it to Check and should work the same as not defining property at all.`

the other non-null related issues are most likely caused by how javadoc is written, like the MAX_VALUE where @romani said we need to really copy-paste the value of it into javadoc s.t. people can simply copy-paste it into their configuration.
@gaurabdg (@romani if this fits you) - can you create issues for each check we found out so far where the javadoc is not behaving as we think it should s.t. those are tracked correctly and can be included in the subsequent release of CS?

**Comment by gaurabdg** [comment]
> yes, i believe we agree on the null issue and we should definitely fix that one.

Isnt this a solution?
```
      if (!"null".equals(modulePropertyDetails.getDefaultValue())) {
            param.setDefaultValue(modulePropertyDetails.getDefaultValue());
        }
```

This actually causes the param to have `null` value since its not being set.

**Comment by muhlba91** [comment]
yes, this is good enough, please add it to metadata-gen s.t. it applies to all plugins using the library.

**Comment by gaurabdg** [comment]
> yes, this is good enough, please add it to metadata-gen s.t. it applies to all plugins using the library.

Sure, @romani hope you are also okay with it.

**Comment by romani** [comment]
> this prevents release of checkstyle/sonar-checkstyle#302

@muhlba91 , please disable metadata loading for now and please do update of metadata in old way and do release.
please activate metadata loading again after release to let us fix it in next release.

**Comment by romani** [comment]
@gaurabdg , please proceed with `null` (hack in metadata-get) and `MAX_VALUE` (update in chekstyle javadoc) like updates.

**Comment by gaurabdg** [comment]
This has been fixed by:
metadata-gen PR: https://github.com/checkstyle/metadata-gen/pull/57
checkstyle PR: https://github.com/checkstyle/checkstyle/pull/8720
