### ISSUE TITLE
MAJOR: Check Names

### ISSUE THREAD

**Issue by muhlba91** [checkstyle/metadata-gen#55]
All check names contain the suffix `Check`. (See s
<img width="1027" alt="Screenshot 2020-08-18 at 17 46 13" src="https://user-images.githubusercontent.com/653739/90535037-beb4c880-e17a-11ea-8ca4-6914ebc53ac7.png">
creenshot)

**Comment by muhlba91** [comment]
this should be fixed before the release of https://github.com/checkstyle/sonar-checkstyle/issues/302

**Comment by gaurabdg** [comment]
@muhlba91 https://github.com/checkstyle/sonar-checkstyle/pull/312
