### ISSUE TITLE
SQ Plugin: Formatting

### ISSUE THREAD

**Issue by muhlba91** [checkstyle/metadata-gen#56]
Basically, we cannot render HTML in SQ's parameter descriptions and javadoc tags in general.

This has to be taken as is but in the following check (LocalVariableNameCheck) something interesting happens. Please investigate.

@romani I am also not sure if parameter descriptions should contain code and a lot of HTML rather than being kept short and descriptive?

<img width="1103" alt="Screenshot 2020-08-18 at 17 49 44" src="https://user-images.githubusercontent.com/653739/90535481-37b42000-e17b-11ea-8ec0-23c443e9f74e.png">

**Comment by gaurabdg** [comment]
@romani How to resolve this? Should we add a nonHTML description to `ModuleDetails`?

**Comment by muhlba91** [comment]
@gaurabdg in general, a good idea but i am more afraid of being able to filter html out efficiently without much overhead now and the time needed to achieve this at this stage. @romani what are your thoughts here?

my honest opinion is that some of the descriptions are just "broken"/"incorrect" in terms of what they are trying to tell you.
in this particlar example i'd actually expect the description of this parameter being moved to the check's description and the parameter's description to be short, concise and easily understandable like "Allow one character variable name in initialization expressions." (if i need more information about it and an example, i can always read the full description of the check.)

in general, not having HTML there would make the parameter description prettier but also not much more readable/less messy in this case. additionally, what about javadoc tags then, like `{@code final}`? do we start filtering everything out or do we just accept some problems there and try to look closer at javadoc comments for checks in the future (e.g. by enforcing guidelines for check and parameter descriptions) to clean them up whenever changes happen?

**Comment by romani** [comment]
problem is only with properties descriptions.
We need to update checkstyle's javadoc to keep property description as simple text and move all code examples to examples, all links to description.

**Comment by gaurabdg** [comment]
Sonar is failing to render html for properties decription, where as check description is working fine, @muhlba91 any idea why?|

**Comment by gaurabdg** [comment]
> problem is only with properties descriptions.
> We need to update checkstyle's javadoc to keep property description as simple text and move all code examples to examples, all links to description.

This will be a huge task, why dont we instead create a html and link less description while scraping only `getHtmlLessDesc()`?

**Comment by romani** [comment]
At least what we can do now - is to remove examples (the most ugly part). 
All other tags (links, .... ) can stay in property description and lets keep it as is, we will think about this later on, or apply smth like `getHtmlLessDesc` in future, we can release with  description like:
![image](https://user-images.githubusercontent.com/812984/90648914-f8bfb200-e1ee-11ea-9a99-90cc3361bda6.png)

**Comment by muhlba91** [comment]
yes, exactly. i believe we need to take some unpretty rendering as given for now but those examples (i think it‘s 2-3 checks actually) should be removed from property description. :)

**Comment by gaurabdg** [comment]
Fixed.
Metadata-gen PR: https://github.com/checkstyle/metadata-gen/pull/58
Checkstyle PR: https://github.com/checkstyle/checkstyle/pull/8733
